### PR TITLE
grpc: fix plan9 build by moving errno matching to a !plan9 file

### LINKED ISSUE #9253: clientconn.go does not compile on plan9 since v1.81.0: undefined syscall.Errno
### What version of gRPC are you using?

v1.81.0 and later (including v1.82.1). v1.80.0 is the last version that works.

### What version of Go are you using (`go version`)?

go 1.26

### What operating system (Linux, Windows, …) and version?

Cross-compiling with `GOOS=plan9` (either GOARCH); host OS doesn't matter.

### What did you do?

```console
$ cat main.go
package main

import _ "google.golang.org/grpc"

func main() {}
$ go get google.golang.org/grpc@v1.82.1
$ GOOS=plan9 go build .
```

### What did you expect to see?

A successful build. grpc-go compiled for plan9 up to and including v1.80.0.

### What did you see instead?

```
# google.golang.org/grpc
clientconn.go:1577:21: undefined: syscall.Errno
clientconn.go:1585:30: undefined: syscall.ECONNRESET
clientconn.go:1589:30: undefined: syscall.ECONNABORTED
```

### Cause

`disconnectErrorString()`, added in #8973 (gRFC A94 subchannel disconnection metrics), uses `syscall.Errno`, `syscall.ECONNRESET` and `syscall.ETIMEDOUT`/`syscall.ECONNABORTED` directly in `clientconn.go`, which is built on every platform. plan9 is the only GOOS whose `syscall` package has none of these - it reports errors as `syscall.ErrorString` rather than numeric `Errno` (linux, darwin, windows, the BSDs, js and wasip1 all define them).

### Suggested fix

Move the errno-dependent classification into a small helper with build tags, following the pattern already used in `internal/syscall`: the real implementation under `//go:build !plan9` (or an allowlist), and a plan9 fallback that skips the errno cases and returns the generic `fmt.Sprintf("Error: %v", err)` string.

I'm happy to send a PR along these lines if this would be accepted.

### Context

Found via rclone's CI, which ships plan9 binaries (rclone/rclone). We've pinned to v1.80.0 for now, but grpc is an indirect dependency for us via `google.golang.org/api`, so the pin also holds back the Google Drive and Google Cloud Storage backends - a fix would be much appreciated.

### PR DESCRIPTION
**Pull request by Yusufihsangorgel**
Fixes #9253

`disconnectErrorString` (added for gRFC A94 in #8973) references `syscall.Errno`, `syscall.ECONNRESET` and `syscall.ECONNABORTED`, none of which exist on plan9, so `GOOS=plan9 go build` fails on every release since v1.81.0.

This moves the error-to-label classification into `disconnectErrorLabel` with two implementations: a `!plan9` file with the existing errno matching, unchanged in behavior, and a plan9 file that keeps the portable classifications (`subchannel shutdown`, `connection timed out`, `unknown`). Only plan9 is excluded so the errno granularity on js/wasm and wasip1, where `syscall.Errno` exists, stays as it is today.

Verified `GOOS=plan9 GOARCH=amd64 go build ./...` fails on master and passes with this change, and `go build` plus the root package tests still pass on linux and darwin.

RELEASE NOTES:

* grpc: fix compilation on plan9, broken since v1.81.0

### CODE REVIEW

**Comment by ncw** [comment]
Thanks for fixing this @Yusufihsangorgel - this is stopping us upgrading rclone to 1.82.1 to pick up the security fix.

**Comment by Yusufihsangorgel** [comment]
Thanks Nick, glad it unblocks the rclone upgrade. The change passes all the test and build checks; the only red is the Validate PR label gate, which is waiting on a grpc-go maintainer to add a `Type:` label. Happy to adjust anything a reviewer wants.

File: clientconn_disconnect_reason_noplan9.go
Comment (easwars) [inline clientconn_disconnect_reason_noplan9.go:1]: Nit: Can we name this file `clientconn_disconnect_reason.go` and similarly for the file below. Thanks.

**Review by easwars — APPROVED** [review]

**Comment by easwars** [comment]
@mbissa For second set of eyes

We would also need this to be cherry-picked before we push the 1.83 release.

File: clientconn_errors_plan9.go [hunk 1]
```diff
@@ -0,0 +1,41 @@
+//go:build plan9
```
Comment (arjan-bal) [inline clientconn_errors_plan9.go]: This build tag is likely redundant since the file already has an _OS suffix. See the [Go documentation on build constraints](https://pkg.go.dev/cmd/go#hdr-Build_constraints) for details.

File: clientconn_disconnect_reason_noplan9.go
Comment (arjan-bal) [reply clientconn_disconnect_reason_noplan9.go:1]: We should use the `_noplan9.go` suffix to remain consistent with other OS-specific code in the repository. Note that, practically speaking, `_noOS.go` suffixes have no effect on compilation.

**Comment by Yusufihsangorgel** [comment]
Done. Renamed both files to `clientconn_disconnect_reason_plan9.go` and `clientconn_disconnect_reason_noplan9.go`, and dropped the `//go:build plan9` constraint since the `_plan9.go` suffix already implies it. I kept the `//go:build !plan9` constraint on the noplan9 file, since as you noted the `_noplan9.go` suffix has no effect on compilation. `GOOS=plan9 GOARCH=amd64 go build ./...` still passes.

**Review by arjan-bal — APPROVED** [review]
LGTM, thanks for the contribution!
