### ISSUE TITLE
clientconn.go does not compile on plan9 since v1.81.0: undefined syscall.Errno

### ISSUE THREAD

**Issue by ncw** [grpc/grpc-go#9253]
### What version of gRPC are you using?

v1.81.0 and later (including v1.82.1). v1.80.0 is the last version that works.

### What version of Go are you using (`go version`)?

go 1.26

### What operating system (Linux, Windows, …) and version?

Cross-compiling with `GOOS=plan9` (either GOARCH); host OS doesn't matter.

### What did you do?

```console
$ cat main.go
package main

import _ "google.golang.org/grpc"

func main() {}
$ go get google.golang.org/grpc@v1.82.1
$ GOOS=plan9 go build .
```

### What did you expect to see?

A successful build. grpc-go compiled for plan9 up to and including v1.80.0.

### What did you see instead?

```
# google.golang.org/grpc
clientconn.go:1577:21: undefined: syscall.Errno
clientconn.go:1585:30: undefined: syscall.ECONNRESET
clientconn.go:1589:30: undefined: syscall.ECONNABORTED
```

### Cause

`disconnectErrorString()`, added in #8973 (gRFC A94 subchannel disconnection metrics), uses `syscall.Errno`, `syscall.ECONNRESET` and `syscall.ETIMEDOUT`/`syscall.ECONNABORTED` directly in `clientconn.go`, which is built on every platform. plan9 is the only GOOS whose `syscall` package has none of these - it reports errors as `syscall.ErrorString` rather than numeric `Errno` (linux, darwin, windows, the BSDs, js and wasip1 all define them).

### Suggested fix

Move the errno-dependent classification into a small helper with build tags, following the pattern already used in `internal/syscall`: the real implementation under `//go:build !plan9` (or an allowlist), and a plan9 fallback that skips the errno cases and returns the generic `fmt.Sprintf("Error: %v", err)` string.

I'm happy to send a PR along these lines if this would be accepted.

### Context

Found via rclone's CI, which ships plan9 binaries (rclone/rclone). We've pinned to v1.80.0 for now, but grpc is an indirect dependency for us via `google.golang.org/api`, so the pin also holds back the Google Drive and Google Cloud Storage backends - a fix would be much appreciated.
