### ISSUE TITLE
broke builds on Go <1.12.0

### ISSUE THREAD

**Issue by alextarrell** [grpc/grpc-go#3775]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.31.0

### What version of Go are you using (`go version`)?
1.11.13

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
`go build ...`

### What did you expect to see?
Things to build to completion

### What did you see instead?
```
# google.golang.org/grpc/credentials
../../credentials/tls.go:245:2: undefined: tls.TLS_AES_128_GCM_SHA256
../../credentials/tls.go:246:2: undefined: tls.TLS_AES_256_GCM_SHA384
../../credentials/tls.go:247:2: undefined: tls.TLS_CHACHA20_POLY1305_SHA256
```
Looks like it was specifically [these](https://github.com/grpc/grpc-go/commit/bc714cd8aeaa4f1a59e055b5a6411a04b17fd319) additions that broke things.

**Comment by codyoss** [comment]
This seems to be breaking users of Go cloud client libraries.

**Comment by menghanl** [comment]
Can you confirm this is happening with `1.31.0`?
The commit causes the failure isn't included in the release.
This should only happen at HEAD (and we will fix that). If it happens with the release, that's a much bigger problem.

**Comment by codyoss** [comment]
From my testing this was an issue with bc714cd8aeaa4f1a59e055b5a6411a04b17fd319, not 1.31.0.

**Comment by amaraliou** [comment]
Any updates on this? I have a similar error when trying to build in CircleCI for integration tests:
```bash
# google.golang.org/grpc/internal/credentials
../../../google.golang.org/grpc/internal/credentials/spiffe.go:34:70: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
../../../google.golang.org/grpc/internal/credentials/spiffe.go:38:47: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
../../../google.golang.org/grpc/internal/credentials/spiffe.go:56:35: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
```

**Comment by menghanl** [comment]
Fixed by https://github.com/grpc/grpc-go/pull/3776
