### ISSUE TITLE
go get failing with cfg.Clone undefined error

### ISSUE THREAD

**Issue by blakeyc** [grpc/grpc-go#1109]
`go version go1.8 darwin/amd64`

Running: `go get google.golang.org/grpc`

Produces error:
```
# google.golang.org/grpc/credentials
../../../google.golang.org/grpc/credentials/credentials_util_go18.go:52: cfg.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
# golang.org/x/net/http2
../../../golang.org/x/net/http2/go18.go:15: c.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
../../../golang.org/x/net/http2/go18.go:17: undefined: http.Pusher
../../../golang.org/x/net/http2/go18.go:20: undefined: http.PushOptions
../../../golang.org/x/net/http2/go18.go:31: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
../../../golang.org/x/net/http2/go18.go:32: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
../../../golang.org/x/net/http2/go18.go:41: undefined: http.ErrAbortHandler
../../../golang.org/x/net/http2/go18.go:45: req.GetBody undefined (type *http.Request has no field or method GetBody)
../../../golang.org/x/net/http2/go18.go:49: undefined: http.NoBody
```

Any ideas how to fix?

**Comment by tamird** [comment]
There is something wrong with your Go installation; your standard library is missing methods from 1.8.

I'm not sure how you managed to create this situation, but I'm guessing you're sharing GOROOT with an earlier version of Go.

**Comment by blakeyc** [comment]
Bingo, thank you. Yes forgot to switch the GOROOT when upgrading to 1.8.

All fixed thanks.
